agent_config:
  action_atoms: 3
  ae_temp: 0.5
  batch_size: 34
  discount: 0.999
  discrete_action_atoms: 3
  double_dqn: true
  dueling: true
  episode_length: 1024
  eps: 1.0
  eps_decay: 0.999999
  eps_min: 0.1
  expl_noise_sd: 0.01
  greedy_eps_testing: 0.0
  iqn: true
  k_huber: 1
  noisy_net: true
  noisy_net_sigma: 0.5
  nTau1: 32
  nTau2: 8
  nstep_return: 5
  nsteps: 1000000
  replay_min_size: 20000
  replay_size: 100000
  reward_clip: &id001 !!python/tuple
  - -1.0
  - 1.0
  tau_embed_size: 64
  tau_soft_update: 0.0001
  train_freq: 4
  unit_size_proportion_avM: 0.05
  proximal_portfolio_penalty: .5
  target_entropy_ratio: 0.98
  learn_entropy_temp: false
  entropy_temp: 0.2
  transaction_thresh: 0.02
agent_type: DQN
basepath: /media/hemu/Data/madigan/experiments/
data_source_config:
  amp:
  - 1.
  - 1.
  - 2.
  dX: 0.01
  freq:
  - 3.
  - 3.
  - 1.
  mu:
  - 5.
  - 5.
  - 8.
  noise: .1
  phase:
  - 0.0
  - 0.5
  - 0.0
data_source_type: Synth
discrete_action_atoms: 3
discrete_actions: true
env_type: Synth
experiment_id: DQN_Synth_Pair_plusLow_freq_Noise.1trans.02_Sortino
init_cash: 1000000
log_freq: 10000
lot_unit_value: 10000
maintenance_margin: 0.25
min_tf: 64
model_config:
  action_atoms: 3
  actor_model_class: ConvPolicySACD
  act_fn: gelu
  channels:
  - 32
  - 32
  compression_factor: 4
  critic_model_class: TwinQNetwork
  curl_momentum_update: 0.001
  curl_lr: .001
  d_model: 1024
  dilations:
  - 1
  - 1
  discrete_action_atoms: 3
  discrete_actions: true
  dueling: true
  iqn: true
  kernels:
  - 5
  - 5
  curl_latent_size: 64
  lot_unit_value: 10000
  min_tf: 64
  model_class: ConvNet
  nTau1: 32
  nTau2: 8
  n_layers: 4
  preserve_window_len: true
  random_crop_ratio: .7
  strides:
  - 1
  - 1
  tau_embed_size: 64
model_save_freq: 64000
n_assets: 1
optim_config:
  betas: !!python/tuple
  - 0.9
  - 0.999
  eps: 1.0e-08
  lr: 0.001
  lr_actor: 0.001
  lr_critic: 0.001
  momentum: 0.9
  type: Adam
  weight_decay: 0
parent_id: ''
preprocessor_config:
  preprocessor_type: StackerDiscrete
  window_length: 64
  norm: true
  norm_type: standard_normal
  timeframes:
  - 64
preprocessor_type: StackerDiscrete
required_margin: 1.0
reward_clip: *id001
reward_shaper_config:
  reward_shaper: SortinoFixedWindow
  window: 1000
slippage_abs: 0.0
slippage_rel: 0.0
test_freq: 2000
test_steps: 4096
train_steps: 100000
transaction_cost_abs: 0.0
transaction_cost_rel: 0.02
