# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dash/dash_synth1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1142, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PlotsWidget = QtWidgets.QWidget(self.centralwidget)
        self.PlotsWidget.setGeometry(QtCore.QRect(230, 80, 771, 531))
        self.PlotsWidget.setObjectName("PlotsWidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 570, 211, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.PlotOptionsWidget = QtWidgets.QWidget(self.centralwidget)
        self.PlotOptionsWidget.setGeometry(QtCore.QRect(1000, 80, 141, 151))
        self.PlotOptionsWidget.setObjectName("PlotOptionsWidget")
        self.PlotOptionsLabel = QtWidgets.QLabel(self.PlotOptionsWidget)
        self.PlotOptionsLabel.setGeometry(QtCore.QRect(0, 0, 111, 21))
        self.PlotOptionsLabel.setObjectName("PlotOptionsLabel")
        self.PlotsLabel = QtWidgets.QLabel(self.centralwidget)
        self.PlotsLabel.setGeometry(QtCore.QRect(230, 60, 681, 17))
        self.PlotsLabel.setObjectName("PlotsLabel")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 80, 211, 491))
        self.widget.setObjectName("widget")
        self.ControlsGridLayout = QtWidgets.QGridLayout(self.widget)
        self.ControlsGridLayout.setContentsMargins(0, 0, 0, 0)
        self.ControlsGridLayout.setObjectName("ControlsGridLayout")
        self.ParamsEdit = QtWidgets.QTextEdit(self.widget)
        self.ParamsEdit.setObjectName("ParamsEdit")
        self.ControlsGridLayout.addWidget(self.ParamsEdit, 2, 0, 1, 2)
        self.FileOpenButton = QtWidgets.QPushButton(self.widget)
        self.FileOpenButton.setObjectName("FileOpenButton")
        self.ControlsGridLayout.addWidget(self.FileOpenButton, 1, 1, 1, 1)
        self.FilenameLabel = QtWidgets.QLabel(self.widget)
        self.FilenameLabel.setObjectName("FilenameLabel")
        self.ControlsGridLayout.addWidget(self.FilenameLabel, 1, 0, 1, 1)
        self.FileSaveButton = QtWidgets.QPushButton(self.widget)
        self.FileSaveButton.setObjectName("FileSaveButton")
        self.ControlsGridLayout.addWidget(self.FileSaveButton, 3, 1, 1, 1)
        self.DiscreteChoice = QtWidgets.QComboBox(self.widget)
        self.DiscreteChoice.setObjectName("DiscreteChoice")
        self.DiscreteChoice.addItem("")
        self.DiscreteChoice.addItem("")
        self.ControlsGridLayout.addWidget(self.DiscreteChoice, 0, 1, 1, 1)
        self.ConfigLabel = QtWidgets.QLabel(self.widget)
        self.ConfigLabel.setObjectName("ConfigLabel")
        self.ControlsGridLayout.addWidget(self.ConfigLabel, 0, 0, 1, 1)
        self.RunCommand = QtWidgets.QPushButton(self.widget)
        self.RunCommand.setObjectName("RunCommand")
        self.ControlsGridLayout.addWidget(self.RunCommand, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1142, 22))
        self.menubar.setObjectName("menubar")
        self.menuDash_Synth = QtWidgets.QMenu(self.menubar)
        self.menuDash_Synth.setObjectName("menuDash_Synth")
        MainWindow.setMenuBar(self.menubar)
        self.menuDash_Synth.addSeparator()
        self.menuDash_Synth.addSeparator()
        self.menubar.addAction(self.menuDash_Synth.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PlotOptionsLabel.setText(_translate("MainWindow", "Plot Options"))
        self.PlotsLabel.setText(_translate("MainWindow", "Plots"))
        self.ParamsEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{\'name\': \'run0\',</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\'discrete_actions\': true,</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\'action_atoms\':11</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\'nsteps\':100</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">}</p></body></html>"))
        self.FileOpenButton.setText(_translate("MainWindow", "Open Config"))
        self.FilenameLabel.setText(_translate("MainWindow", "config.json"))
        self.FileSaveButton.setText(_translate("MainWindow", "Save"))
        self.DiscreteChoice.setItemText(0, _translate("MainWindow", "Discrete"))
        self.DiscreteChoice.setItemText(1, _translate("MainWindow", "Continuous"))
        self.ConfigLabel.setText(_translate("MainWindow", "Config"))
        self.RunCommand.setText(_translate("MainWindow", "Run"))
        self.menuDash_Synth.setTitle(_translate("MainWindow", "Dash-Synth"))
